import type {NextPage} from 'next';
import {useSession, signIn} from 'next-auth/react';
import Head from 'next/head';
import {trpc} from '../utils/trpc';
import {customAlphabet} from 'nanoid';
import {useRouter} from 'next/router';

const nanoid = customAlphabet('1234567890', 8);

const Home: NextPage = () => {
    const router = useRouter();

    const createRoom = () => {
        const roomId = nanoid();

        router.push(`/rooms/${roomId}`);
    };

    return (
        <div>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="w-screen min-h-screen flex flex-col justify-center items-center p-4 overflow-y-scroll">
                <button onClick={createRoom}>Create Room</button>
            </div>
        </div>
    );
};

export default Home;
