import type {NextPage} from 'next';
import {useSession, signIn} from 'next-auth/react';
import Head from 'next/head';
import {trpc} from '../utils/trpc';
import {customAlphabet} from 'nanoid';
import {useRouter} from 'next/router';

const nanoid = customAlphabet('1234567890', 8);

const Home: NextPage = () => {
    const router = useRouter();

    const createRoom = () => {
        const roomId = nanoid();

        router.push(`/rooms/${roomId}`);
    };

    return (
        <div>
            <Head>
                <title>Ding! Messenger</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="w-screen min-h-screen flex flex-col justify-center items-center p-4 overflow-y-scroll bg-light">
                <button
                    className="text-3xl bg-accent text-light rounded-lg p-10 hover:scale-110 duration-150"
                    onClick={createRoom}
                >
                    Create Room
                </button>
            </div>
        </div>
    );
};

export default Home;
